### ISSUE TITLE
Update dependencies 😅

### ISSUE THREAD

**Issue by mesqueeb** [egoist/presite#27]
Hi
i think this node app is the best SPA pre-render solution because it's so easy to use and understand. No webpack required!

I'd love the dependencies to be updated! 😉

**Comment by egoist** [comment]
If you install this package the dependencies should be up-to-date 😄

**Comment by mesqueeb** [comment]
@egoist but don't these bother you...? 😅 

BTW, your package works like a charm. I love it. Big fan here.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/3253920/65882987-1dd9e500-e3d1-11e9-9d60-470b1717b5e1.png">

**Comment by egoist** [comment]
Dependencies are updated.
