### ISSUE TITLE
Prerender Detection

### ISSUE THREAD

**Issue by redxtech** [egoist/presite#82]
Hello!

Is there any way for the app to tell whether it's being prerendered? I know that with `react-snap` you can check with `navigator.userAgent === 'ReactSnap'`, so I'm wondering if there's an equivalent for this prerenderer.

I ask because I would like to add a few additional detection methods to the PR that I am going to be submitting on your `vue-client-only` component. I tested `presite` with `vue-client-only`, but unless I am missing something, it does not appear to work.

Thanks :)

**Comment by tradchenko** [comment]
> Hello!
> 
> Is there any way for the app to tell whether it's being prerendered? I know that with `react-snap` you can check with `navigator.userAgent === 'ReactSnap'`, so I'm wondering if there's an equivalent for this prerenderer.
> 
> I ask because I would like to add a few additional detection methods to the PR that I am going to be submitting on your `vue-client-only` component. I tested `presite` with `vue-client-only`, but unless I am missing something, it does not appear to work.
> 
> Thanks :)

@redxtech
Hi! You can use `if(navigator.userAgent.includes('Prerender')) { //you code }`

**Comment by egoist** [comment]
👆 is right.
